services:
  - type: web
    name: visman-api
    rootDir: server
    env: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: "/api/health"
    envVars:
      - key: PORT
        value: "3001"
      # Optional email notifications. Fill in on Render Dashboard or set sync: false to provide securely.
      # - key: SMTP_HOST
      #   sync: false
      # - key: SMTP_PORT
      #   value: "587"
      # - key: SMTP_USER
      #   sync: false
      # - key: SMTP_PASS
      #   sync: false
      # - key: NOTIFY_TO
      #   value: "nnamelekelechi9@gmail.com"
      # - key: MAIL_FROM
      #   value: "Visman <no-reply@visman.local>"
